--Q16. Customer Lifetime value (CLV)
-- Calculate the total revenue generated by each customer over all their orders
SELECT 
	o.customer_id,
	c.name,
	Round(SUM(o.total_amount)::NUMERIC,2) as CLV
FROM orders as o
JOIN customers as c
on o.customer_id = c.customer_id
Group by 1,2
Order  by 1
